version: '3.5'

services:
  mariadb:
    env_file:
      - ../.env
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:abouazi
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    networks:
     - g_network
    ports:
      - "3306:3306"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:abouazi
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html
    networks:
      - g_network
    ports:
      - '443:443'

  wordpress:
    env_file:
      - ../.env
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:abouazi
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp_volume:/var/www/html
    networks:
      - g_network
    ports:
      - "9000:9000"

volumes:
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      device: /home/abouazi/data/wp
      type: none
      o: bind

  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      device: /home/abouazi/data/db
      type: none
      o: bind

networks:
  g_network:
   name: g_network

